name: COBOL in the Cloud
on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install GnuCOBOL
        run: |
          sudo apt-get update
          sudo apt-get install -y gnucobol

      - name: Compile and Run
        run: |
          # The -free flag ignores the 1950s punch-card column rules
          # The -x flag creates an executable
          cobc -x -free hello.cob
          ./hello
