name: COBOL in the Cloud
on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GnuCOBOL
        run: |
          sudo apt-get update
          sudo apt-get install -y gnucobol

      - name: Compile and Run
        run: |
          cobc -x -free math.cob
          # Passing 12 and 5 as arguments
          ./math 12 5
